import type { Metadata } from "next";
import { Nunito } from 'next/font/google'
import "./globals.css";
import  Header  from "@/Layouts/Header/Header";
import Footer from "@/Layouts/Footer/Footer";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // add more weights if needed
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en"  className={nunito.className}>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>



  );

}
